
package View;

import Modelagem.DAO;
import Modelagem.FicheiroDat;
import Modelagem.Manuais;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio joao zimila
 */
public class CadastroManuais extends javax.swing.JFrame {

    /**
     * Creates new form CadastroManuais
     */
    private DefaultTableModel  modelo;
    FicheiroDat f =new FicheiroDat();
    ArrayList<Object> manuaisFicheiro = f.leitura("Manuais.dat");
    
    public void popular(){
    DAO dao = new DAO();
    modelo.setNumRows(0);
   // modelo.fireTableDataChanged();
//    jTableManuais.updateUI();
    for(Manuais m: dao.selecTudo()){
    modelo.addRow(new Object[]{m.getId(),m.getNome(),m.getClasse(),m.getEditora(),m.getLocalizacao()});
        
    }
   }
     
    public CadastroManuais() {
        
        initComponents();
        
    String [] colunas = {"ID","Nome","Editora","Classe","Location"};
     modelo = new DefaultTableModel();
     modelo.setColumnIdentifiers(colunas);
     jTableManuais.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelManuais = new javax.swing.JPanel();
        LabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxClasses = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLocalizacao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEditora = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManuais = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelManuais.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelNome.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Classe:");

        jComboBoxClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a classe", "8 Classe", "9 Classe", "10 Classe", "11 Classe", "12 Classe" }));
        jComboBoxClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClassesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Loc:");

        jComboBoxLocalizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a pratileira", "A", "B", "C", "D", "E" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Editora:");

        jComboBoxEditora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a editora", "Pural", "LongMan", "Texto Editores" }));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Deletar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelManuaisLayout = new javax.swing.GroupLayout(painelManuais);
        painelManuais.setLayout(painelManuaisLayout);
        painelManuaisLayout.setHorizontalGroup(
            painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManuaisLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManuaisLayout.createSequentialGroup()
                        .addComponent(LabelNome)
                        .addGap(18, 18, 18))
                    .addGroup(painelManuaisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)))
                .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelManuaisLayout.createSequentialGroup()
                        .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxClasses, 0, 228, Short.MAX_VALUE)
                            .addComponent(txtNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31))
                    .addGroup(painelManuaisLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxLocalizacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxEditora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManuaisLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        painelManuaisLayout.setVerticalGroup(
            painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManuaisLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(LabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEditora))
                .addGap(30, 30, 30)
                .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxClasses)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLocalizacao))
                .addGap(55, 55, 55)
                .addGroup(painelManuaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(8, 8, 8))
        );

        jTableManuais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableManuais);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-adicionar-livro-64.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastrar Novos Manuais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelManuais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(painelManuais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String nome =txtNome.getText();
     String classe="";
       String editora="";
       String loc="";
     if(jComboBoxClasses.getSelectedIndex()==0){
       classe="8 Classe";  
     }else if(jComboBoxClasses.getSelectedIndex()==1){
         classe="9 Classe";
     }else if(jComboBoxClasses.getSelectedIndex()==2){
         classe="10 Classe";
     }else if(jComboBoxClasses.getSelectedIndex()==3){
         classe="11 Classe";
     }else if(jComboBoxClasses.getSelectedIndex()==4){
         classe="12 Classe";
     }
   
     if(jComboBoxEditora.getSelectedIndex()==0){
        editora="Plural"; 
     }else if(jComboBoxEditora.getSelectedIndex()==1){
         editora="LongMan";
     }else if(jComboBoxEditora.getSelectedIndex()==2){
         editora="Texto Editores";
     }
     if(jComboBoxLocalizacao.getSelectedIndex()==0){
         loc="A";
     }else if(jComboBoxLocalizacao.getSelectedIndex()==1){
        loc="B";  
     }else if(jComboBoxLocalizacao.getSelectedIndex()==2){
         loc="C"; 
     }
    
     //passando os dados para o ficheiro dat
     manuaisFicheiro.add(new Manuais(nome,classe,editora,loc));
     f.escrever(manuaisFicheiro,"Manuais.dat");
     //gravando os dados no banco de dados
      Manuais m1 =new Manuais(nome,classe,editora,loc);
      DAO.guardar(m1);
      
     //passando o ultimo dados cadastrado para tabela
       popular();
      txtNome.setText("");  
     
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClassesActionPerformed
     
    }//GEN-LAST:event_jComboBoxClassesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

     
     //Removendo os dados do banco de dados
      Manuais manuais = new Manuais();
      int ID = (int) jTableManuais.getValueAt(jTableManuais.getSelectedRow(),0);
      System.out.println(ID);
      manuais.setId(ID);
      DAO.deletar(manuais);
      
       //Removendo os dados da tabela
     int id = jTableManuais.getSelectedRow();
     modelo.removeRow(id);
     modelo.fireTableDataChanged();
     jTableManuais.updateUI();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String nome =txtNome.getText();
     String classe="";
      String editora="";
     String loc="";
     if(jComboBoxClasses.getSelectedIndex()==1){
       classe="8 Classe";  
     }else if(jComboBoxClasses.getSelectedIndex()==2){
         classe="9 Classe";
     }else if(jComboBoxClasses.getSelectedIndex()==2){
         classe="10 Classe";
     }else if(jComboBoxClasses.getSelectedIndex()==3){
         classe="11 Classe";
     }else if(jComboBoxClasses.getSelectedIndex()==5){
         classe="12 Classe";
     }
    
     if(jComboBoxEditora.getSelectedIndex()==1){
        editora="Plural"; 
     }else if(jComboBoxEditora.getSelectedIndex()==2){
         editora="LongMan";
     }else if(jComboBoxEditora.getSelectedIndex()==3){
         editora="Texto Editores";
     }
     
      if(jComboBoxLocalizacao.getSelectedIndex()==1){
         loc="A";
     }else if(jComboBoxLocalizacao.getSelectedIndex()==2){
        loc="B";  
     }else if(jComboBoxLocalizacao.getSelectedIndex()==3){
         loc="C"; 
     }
     //Alterando os dados no banco de dados
     int ID = (int) jTableManuais.getValueAt(jTableManuais.getSelectedRow(),0);
     Manuais m = new Manuais(nome,classe,editora,loc,ID);
     DAO.atualizar(m);
     
     //Alterando os dados na tabela
                
   if(jTableManuais.getSelectedRow()!=-1){
                        
   jTableManuais.setValueAt(ID,jTableManuais.getSelectedRow(), 0);
   jTableManuais.setValueAt(nome,jTableManuais.getSelectedRow(), 1);
   jTableManuais.setValueAt(classe,jTableManuais.getSelectedRow(),2);
   jTableManuais.setValueAt(editora,jTableManuais.getSelectedRow(),3);
   jTableManuais.setValueAt(loc,jTableManuais.getSelectedRow(),4);
   modelo.fireTableDataChanged();
                       
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroManuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroManuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroManuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroManuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroManuais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxClasses;
    private javax.swing.JComboBox<String> jComboBoxEditora;
    private javax.swing.JComboBox<String> jComboBoxLocalizacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableManuais;
    private javax.swing.JPanel painelManuais;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
