/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Antonio joao zimila
 */
public class NiveisDeAcesso extends javax.swing.JFrame {

    /**
     * Creates new form NiveisDeAcesso
     */
    public NiveisDeAcesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel1Niveis = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ImageIcon imgFundo = new ImageIcon(getClass().getResource("/PapeisDEParede/FundoNiveis.jpg"));
        Image image=imgFundo.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintcomponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        botaoEstudantes = new javax.swing.JButton();
        botaoFuncionarios = new javax.swing.JButton();
        botaoAdministradores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        Painel1Niveis.setBackground(new java.awt.Color(0, 255, 51));
        Painel1Niveis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NIVEIS DE ACESSO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-centro-de-estudos-64.png"))); // NOI18N

        javax.swing.GroupLayout Painel1NiveisLayout = new javax.swing.GroupLayout(Painel1Niveis);
        Painel1Niveis.setLayout(Painel1NiveisLayout);
        Painel1NiveisLayout.setHorizontalGroup(
            Painel1NiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1NiveisLayout.createSequentialGroup()
                .addGroup(Painel1NiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1NiveisLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Painel1NiveisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Painel1NiveisLayout.setVerticalGroup(
            Painel1NiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1NiveisLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione um nivel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        botaoEstudantes.setBackground(new java.awt.Color(0, 0, 0));
        botaoEstudantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoEstudantes.setForeground(new java.awt.Color(255, 255, 255));
        botaoEstudantes.setText("ESTUDANTES");
        botaoEstudantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEstudantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEstudantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEstudantesMouseExited(evt);
            }
        });
        botaoEstudantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstudantesActionPerformed(evt);
            }
        });

        botaoFuncionarios.setBackground(new java.awt.Color(0, 0, 0));
        botaoFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        botaoFuncionarios.setText("FUNCIONARIOS");
        botaoFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFuncionariosMouseExited(evt);
            }
        });
        botaoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFuncionariosActionPerformed(evt);
            }
        });

        botaoAdministradores.setBackground(new java.awt.Color(0, 0, 0));
        botaoAdministradores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoAdministradores.setForeground(new java.awt.Color(255, 255, 255));
        botaoAdministradores.setText("ADMINISTRADORES");
        botaoAdministradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAdministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAdministradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAdministradoresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAdministradores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoEstudantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(botaoEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(botaoFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(botaoAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1Niveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel1Niveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFuncionariosActionPerformed
      Login1 l = new Login1();
      l.setVisible(true);
    }//GEN-LAST:event_botaoFuncionariosActionPerformed

    private void botaoEstudantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstudantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEstudantesActionPerformed

    private void botaoEstudantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEstudantesMouseEntered
      botaoEstudantes.setBackground(Color.white);
      botaoEstudantes.setForeground(Color.BLACK);
    }//GEN-LAST:event_botaoEstudantesMouseEntered

    private void botaoEstudantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEstudantesMouseExited
      botaoEstudantes.setBackground(Color.BLACK);
      botaoEstudantes.setForeground(Color.white);
    }//GEN-LAST:event_botaoEstudantesMouseExited

    private void botaoFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFuncionariosMouseEntered
       botaoFuncionarios.setBackground(Color.white);
       botaoFuncionarios.setForeground(Color.BLACK);
    }//GEN-LAST:event_botaoFuncionariosMouseEntered

    private void botaoFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFuncionariosMouseExited
        botaoFuncionarios.setBackground(Color.BLACK);
        botaoFuncionarios.setForeground(Color.white);
    }//GEN-LAST:event_botaoFuncionariosMouseExited

    private void botaoAdministradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdministradoresMouseEntered
       botaoAdministradores.setBackground(Color.white);
       botaoAdministradores.setForeground(Color.BLACK);
    }//GEN-LAST:event_botaoAdministradoresMouseEntered

    private void botaoAdministradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdministradoresMouseExited
         botaoAdministradores.setBackground(Color.BLACK);
        botaoAdministradores.setForeground(Color.white);
    }//GEN-LAST:event_botaoAdministradoresMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NiveisDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NiveisDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NiveisDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NiveisDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NiveisDeAcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel1Niveis;
    private javax.swing.JButton botaoAdministradores;
    private javax.swing.JButton botaoEstudantes;
    private javax.swing.JButton botaoFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
